// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlfboxorogcafgkokjeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZmJveG9yb2djYWZna29ramVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODgzNDAsImV4cCI6MjA2MTM2NDM0MH0.Ohi958kKpbLGv5xRmwbtyw1nadPUxcZVJf-Jf0VTs9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);